pipeline:
  dockerhub_legacy:
    image: plugins/docker
    repo: iexechub/poco-chain
    secrets: [docker_username, docker_password]
    tags:
      - latest
      - ${DRONE_TAG##lv}
      - legacy-latest
      - legacy-${DRONE_COMMIT_SHA:0:7}
    when:
      ref: [refs/tags/lv*]

  dockerhub_legacy_20s:
    image: plugins/docker
    repo: iexechub/poco-chain
    secrets: [docker_username, docker_password]
    dockerfile: Dockerfile_20sec
    tags:
      - legacy-20s-${DRONE_COMMIT_SHA:0:7}
    when:
      ref: [refs/tags/lv*]

  kovan_legacy:
    image: node:latest
    commands:
      - sed -i '/ethereumjs-util/d' package.json
      - npm install
      - ./node_modules/.bin/truffle migrate --network kovan
    secrets: [deployer_mnemonic]
    when:
      ref: [refs/tags/lv*]

  contracts_min:
    image: node:latest
    commands:
      - mkdir ./build/contracts-min
      - for f in $(ls ./build/contracts); do cat ./build/contracts/$f | ./node_modules/.bin/jqn 'pick(["abi","networks"])' --color=false -j >> ./build/contracts-min/$f; done
    when:
      ref: [refs/tags/lv*]

  npm:
    image: plugins/npm
    secrets: [npm_password]
    username: sulliwane
    email: sulliwane@gmail.com
    tag: next
    when:
      ref: [refs/tags/lv3*]
