pipeline:
  dockerhub_legacy:
    image: plugins/docker
    repo: iexechub/poco-chain
    secrets: [docker_username, docker_password]
    tags:
      - latest
      - ${DRONE_TAG##lv}
      - legacy-latest
      - legacy-${DRONE_COMMIT_SHA:0:7}
    when:
      ref: [refs/tags/lv*]
