pipeline:
  dockerhub_legacy:
    image: plugins/docker
    repo: iexechub/poco-chaintest
    secrets: [docker_username, docker_password]
    build_args:
      - DEV_NODE: http://localhost:8545
      - MNEMONIC: actual surround disorder swim upgrade devote digital misery truly verb slide final
    tags:
      - v5-token-ws
    when:
      branch: [poco-chain-update]
