pipeline:
  docker_token_parity:
    image: plugins/docker
    repo: iexechub/poco-chaintest
    secrets: [docker_username, docker_password]
    dockerfile: Dockerfile
    build_args:
      - DEV_NODE=http://localhost:8545
      - MNEMONIC=actual surround disorder swim upgrade devote digital misery truly verb slide final
    tags:
      - v5-token-parity
    when:
      branch: [poco-chain-update]

  docker_native_parity:
    image: plugins/docker
    repo: iexechub/poco-chaintest
    secrets: [docker_username, docker_password]
    dockerfile: Dockerfile_native
    build_args:
      - DEV_NODE=http://localhost:8545
      - MNEMONIC=actual surround disorder swim upgrade devote digital misery truly verb slide final
    tags:
      - v5-native-parity
    when:
      branch: [poco-chain-update]

  docker_token_ganache:
    image: plugins/docker
    repo: iexechub/poco-chaintest
    secrets: [docker_username, docker_password]
    dockerfile: Dockerfile_token_ganache
    build_args:
      - MNEMONIC=actual surround disorder swim upgrade devote digital misery truly verb slide final
    tags:
      - v5-token
    when:
      branch: [poco-chain-update]

  docker_native_ganache:
    image: plugins/docker
    repo: iexechub/poco-chaintest
    secrets: [docker_username, docker_password]
    dockerfile: Dockerfile_native_ganache
    build_args:
      - MNEMONIC=actual surround disorder swim upgrade devote digital misery truly verb slide final
    tags:
      - v5-native
    when:
      branch: [poco-chain-update]

  docker_token_1s_ganache:
    image: plugins/docker
    repo: iexechub/poco-chaintest
    secrets: [docker_username, docker_password]
    dockerfile: Dockerfile_token_1s_ganache
    tags:
      - v5-token-1s
    when:
      branch: [poco-chain-update]
